export let SERVER_URL = 'https://hits-intership.pujak.ru/api'
export let ROLE_KEY = 'role'
export let ACCESS_TOKEN_KEY = 'access_token'
export let REFRESH_TOKEN_KEY = 'refresh_token'
export let SELECTED_STREAM_KEY = 'selected_stream'
